### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sunsetsonwheels** [khanhas/homebrew-tap#12] opened 2022-03-21 12:47 UTC
OS: macOS 12.3 x86_64
Homebrew version: 3.4.2
Go version: 1.18 (installed from Homebrew)

```
$ brew install khanhas/tap/spicetify-cli
==> Downloading https://github.com/spicetify/spicetify-cli/archive/v2.9.2.tar.gz
Already downloaded: /Users/jkelol111/Library/Caches/Homebrew/downloads/845988b1a7dc84c8858ff2379d31a11136f04b5080d777f93c2b49802fd52faf--spicetify-cli-2.9.2.tar.gz
==> Installing spicetify-cli from khanhas/tap
==> go build -ldflags -X main.version=2.9.2 -o /usr/local/Cellar/spicetify-cli/2.9.2/bin/spicetify
Last 15 lines from /Users/jkelol111/Library/Logs/Homebrew/spicetify-cli/01.go:
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
# golang.org/x/sys/unix
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:28:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:43:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:59:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:75:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:90:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:105:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:121:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:121:3: too many errors

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/khanhas/homebrew-tap/issues
```

**Comment by jorgedel4** [comment] 2022-03-22 18:08
I have the same issue

**Comment by itsmeow** [comment] 2022-03-23 19:26
Go 1.18 is relatively new, I am not sure what causes this issue but there is not much established documentation at the moment. I would suggest downgrading to 1.17.

**Comment by itsmeow** [comment] 2022-03-23 19:37
I cannot reproduce this on Windows with Go 1.18 attempting a manual build.

**Comment by grischard** [comment] 2022-03-24 17:53
Same issue on arm64, which I'm copy-pasting here for googlability:

```
> brew install spicetify-cli
==> Downloading https://github.com/spicetify/spicetify-cli/archive/v2.9.3.tar.gz
Already downloaded: /Users/stereo/Library/Caches/Homebrew/downloads/62d203f35f20f8f486073967799109312a01f93cf7fd6de8d5036425b1de633d--spicetify-cli-2.9.3.tar.gz
==> Installing spicetify-cli from khanhas/tap
==> go build -ldflags -X main.version=2.9.3 -o /opt/homebrew/Cellar/spicetify-cli/2.9.3/bin/spicetify
Last 15 lines from /Users/stereo/Library/Logs/Homebrew/spicetify-cli/01.go:
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
# golang.org/x/sys/unix
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/syscall_darwin.1_13.go:29:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.1_13.go:27:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.1_13.go:40:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:28:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:43:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:59:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:75:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:90:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:105:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:121:3: //go:linkname must refer to declared function or variable
../pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_arm64.go:121:3: too many errors
```

**Comment by grischard** [comment] 2022-03-24 17:56
See also https://github.com/google/go-jsonnet/issues/596 and https://github.com/golang/go/issues/49219

"I believe you have an indirect dependency on an old version of x/sys that breaks when running go install with go 1.18."

**Comment by grischard** [comment] 2022-03-24 18:02
Updating x/sys with `go get -u golang.org/x/sys` fixes it for me.

**Comment by itsmeow** [comment] 2022-03-26 04:24
Fixed by https://github.com/spicetify/spicetify-cli/pull/1547

**Closed as completed by itsmeow** 2022-03-26 04:24 UTC
Labels: bug
